feat: backup and restore scripts for python client
algolia-samples/api-clients-quickstarts pull request #30
Opened 2022-11-17 09:16 UTC by christopherjstock

Add backup.py and restore.py scripts to the python samples. Allows for backup of an index and associated rules, synonyms and settings and restore of the same.

**Contributing to Algolia Samples**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2022-11-24 16:07 UTC, matthewbond requested changes
Code looks great, can you add  descriptions of the files to the readme please? (api-clients-quickstarts/blob/master/python/README.md)

2022-11-28 09:44 UTC, christopherjstock commented
> Code looks great, can you add descriptions of the files to the readme please? (api-clients-quickstarts/blob/master/python/README.md)

README has been updated with links to the new files.

2022-12-01 08:33 UTC, matthewbond approved these changes

2022-12-01 10:53 UTC, matthewbond approved these changes
LGTM!

2022-12-01 10:56 UTC, merged